/**
 * @file uart.h
 * @brief Minimal UART0 bring-up (TX everywhere, RX on the access point)
 *
 * Replaces libmf's uart0_init()/uart_timer0_baud(). Those live in the same
 * object files as UART1's ring buffers and the debug-link machinery, and
 * linking them costs about 86 of the 128 bytes of directly addressable
 * internal RAM on this part - more than the e-paper driver, the NFC driver
 * and the radio driver need between them. See uart.c.
 */

#ifndef UART_H
#define UART_H

#include <ax8052f143.h>
#include <libmftypes.h>

/* Configure UART0 as 8N1 at 38400 bit/s on PB4 (TX) / PB5 (RX), clocked from
 * the 20 MHz FRC oscillator that main() starts, with the rate generated by
 * timer 0. Call it after the oscillator is running; the PB4/PB5 pin setup
 * stays with the caller. */
void uart_begin(void);

/* Receive side, polled: this firmware never sets IE/EA, so there is no UART
 * interrupt to be woken by. uart_rx_ready() is true while a byte is waiting
 * in U0SHREG and uart_getc() takes it and re-arms the receiver - the same
 * two accesses libmf's own UART0 interrupt handler makes. See uart.c for the
 * source those two lines come from. */
uint8_t uart_rx_ready(void) __reentrant;
uint8_t uart_getc(void) __reentrant;

#endif /* UART_H */
