/**
 * @file uart.h
 * @brief Minimal UART0 bring-up (TX as used by every ShelfKit firmware)
 *
 * Replaces libmf's uart0_init()/uart_timer0_baud(). Those live in the same
 * object files as UART1's ring buffers and the debug-link machinery, and
 * linking them costs about 86 of the 128 bytes of directly addressable
 * internal RAM on this part - more than the e-paper driver, the NFC driver
 * and the radio driver need between them. See uart.c.
 */

#ifndef UART_H
#define UART_H

#include <ax8052f143.h>
#include <libmftypes.h>

/* Configure UART0 as 8N1 at 38400 bit/s on PB4 (TX), clocked from the 20 MHz
 * FRC oscillator that main() starts, with the rate generated by timer 0.
 * Call it after the oscillator is running; the PB4/PALTB pin setup stays
 * with the caller. */
void uart_begin(void);

#endif /* UART_H */
